/**
 * Fetch the transcript for a YouTube video by its ID.
 *
 * Returns an object with:
 *   - segments: Array of { text, offset, duration }
 *   - fullText: The entire transcript as a single string
 *
 * Throws a descriptive error if the transcript is unavailable.
 */
async function fetchTranscript(videoId) {
  try {
    const response = await fetch(`https://youtube-transcript.ai/transcript/${videoId}.txt`);

    if (!response.ok) {
      if (response.status === 404) {
        const err = new Error(
          'No transcript found. The video may not have captions available.'
        );
        err.status = 404;
        throw err;
      } else if (response.status === 403) {
        const err = new Error(
          'Transcripts are disabled for this video by the uploader.'
        );
        err.status = 403;
        throw err;
      } else if (response.status === 429) {
        const err = new Error(
          'YouTube is rate-limiting requests. Please try again in a minute.'
        );
        err.status = 429;
        throw err;
      } else {
        const err = new Error(
          'Failed to fetch transcript from the API. Please try again.'
        );
        err.status = 502;
        throw err;
      }
    }

    const markdownText = await response.text();

    if (!markdownText || markdownText.includes('<!DOCTYPE html>') || !markdownText.includes('## Transcript')) {
      const err = new Error(
        'No transcript found. The video may not have captions available.'
      );
      err.status = 404;
      throw err;
    }

    // Find where transcript starts
    const lines = markdownText.split(/\r?\n/);
    const transcriptStartIndex = lines.findIndex(line => line.trim().startsWith('## Transcript'));
    const transcriptLines = transcriptStartIndex !== -1
      ? lines.slice(transcriptStartIndex + 1)
      : lines;

    const segments = [];
    // Timestamp regex: e.g. [0:01] or [1:02:03]
    const timestampRegex = /^\[(?:(\d+):)?(\d+):(\d+)\]\s*(.*)$/;

    for (let line of transcriptLines) {
      line = line.trim();
      if (!line || line.startsWith('---') || line.startsWith('Generated by')) continue;

      const match = line.match(timestampRegex);
      if (match) {
        const hours = match[1] ? parseInt(match[1], 10) : 0;
        const minutes = parseInt(match[2], 10);
        const seconds = parseInt(match[3], 10);
        let text = match[4].trim();

        const offset = hours * 3600 + minutes * 60 + seconds;

        // Clean up text format
        text = text
          .replace(/\r?\n/g, ' ')
          .replace(/\s+/g, ' ')
          .trim();

        if (text.length > 0) {
          segments.push({
            text,
            offset,
            duration: 0
          });
        }
      }
    }

    if (segments.length === 0) {
      const err = new Error(
        'No transcript found or formatting could not be parsed.'
      );
      err.status = 404;
      throw err;
    }

    // Calculate durations based on subsequent segment offsets
    for (let i = 0; i < segments.length; i++) {
      if (i < segments.length - 1) {
        segments[i].duration = Math.max(0, segments[i + 1].offset - segments[i].offset);
      } else {
        segments[i].duration = 5; // default duration for the last segment
      }
    }

    const fullText = segments.map((s) => s.text).join(' ');

    return { segments, fullText };
  } catch (error) {
    if (error.status) throw error;

    const message = error.message || '';
    if (message.includes('fetch')) {
      const err = new Error(
        'Failed to connect to the transcript API. Please check your network connection.'
      );
      err.status = 502;
      throw err;
    }

    const err = new Error(
      'Failed to fetch transcript. Please verify the URL and try again.'
    );
    err.status = 502;
    throw err;
  }
}

module.exports = { fetchTranscript };
