async function fetchTranscript(videoId) {
  try {
    console.log("Fetching transcript for:", videoId);

    const response = await fetch(
      `https://youtube-transcript.ai/transcript/${videoId}.txt`
    );

    if (!response.ok) {
      const err = new Error(`Transcript API returned ${response.status}`);
      err.status = response.status;
      throw err;
    }

    const markdownText = await response.text();

    if (
      !markdownText ||
      markdownText.includes("<!DOCTYPE html>") ||
      !markdownText.includes("## Transcript")
    ) {
      const err = new Error(
        "No transcript found. The video may not have captions available."
      );
      err.status = 404;
      throw err;
    }

    const lines = markdownText.split(/\r?\n/);

    const transcriptStartIndex = lines.findIndex((line) =>
      line.trim().startsWith("## Transcript")
    );

    const transcriptLines =
      transcriptStartIndex !== -1
        ? lines.slice(transcriptStartIndex + 1)
        : lines;

    const segments = [];

    const timestampRegex = /^\[(?:(\d+):)?(\d+):(\d+)\]\s*(.*)$/;

    for (let line of transcriptLines) {
      line = line.trim();

      if (
        !line ||
        line.startsWith("---") ||
        line.startsWith("Generated by")
      ) {
        continue;
      }

      const match = line.match(timestampRegex);

      if (!match) continue;

      const hours = match[1] ? parseInt(match[1], 10) : 0;
      const minutes = parseInt(match[2], 10);
      const seconds = parseInt(match[3], 10);

      const offset = hours * 3600 + minutes * 60 + seconds;

      const text = match[4]
        .replace(/\s+/g, " ")
        .trim();

      if (text) {
        segments.push({
          text,
          offset,
          duration: 0,
        });
      }
    }

    if (segments.length === 0) {
      const err = new Error("No transcript data could be parsed.");
      err.status = 404;
      throw err;
    }

    console.log("========== FIRST 10 SEGMENTS ==========");
    console.log(JSON.stringify(segments.slice(0, 10), null, 2));
    console.log("=======================================");

    for (let i = 0; i < segments.length; i++) {
      if (i < segments.length - 1) {
        segments[i].duration =
          segments[i + 1].offset - segments[i].offset;
      } else {
        segments[i].duration = 5;
      }
    }

    const fullText = segments
      .map((segment) => segment.text)
      .join(" ");

    return {
      segments,
      fullText,
    };
  } catch (error) {
    console.error("YOUTUBE ERROR:", error);

    if (error.status) {
      throw error;
    }

    const err = new Error(
      "Failed to fetch transcript. Please verify the URL and try again."
    );
    err.status = 502;
    throw err;
  }
}

module.exports = { fetchTranscript };
